version: '3'
services:
  db:
    container_name: sorcerer-mysql
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    command: --init-file /data/application/init.sql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - ${MYSQL_HOST_PORT}:${MYSQL_CLIENT_PORT}
    volumes:
      - ${MYSQL_DB_FILES}:/var/lib/mysql
      - ${MYSQL_INIT_FILE}:/data/application/init.sql